server:
  port: 2002
spring:
  application:
    name: seata-storage-service
  cloud:
    nacos:
      discovery:
        # nacos服务注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        # 配置Sentinel dashboard地址
        dashboard: 127.0.0.1:8080
        # 默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719
  #      datasource:
  #        ds:
  #          nacos:
  #            server-addr: 127.0.0.1:8848
  #            dataId: cloudalibaba-sentinel-service
  #            groupId: DEFAULT_GROUP
  #            data-type: json
  #            rule-type: degrade
  #  数据源基本配置
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/seata_storage?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

seata:
  enabled: true
  application-id: ${spring.application.name} # Seata 应用编号，默认为 ${spring.application.name}
  tx-service-group: seata-account-service-group # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  service:   # Seata 服务配置项，对应 ServiceProperties 类
    vgroup-mapping:  # 配置项值为TC集群名（必须与seata-server保持一致）
      seata-account-service-group: default
    disable-global-transaction: false
  registry: # Seata 注册中心配置项，对应 RegistryProperties 类
    type: nacos # 注册中心类型，默认为 file
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: 21e2fe2e-3d5e-449b-9ff2-a87a9345742e
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: 21e2fe2e-3d5e-449b-9ff2-a87a9345742e
      username: nacos
      password: nacos

# mybatis配置
mybatis:
  # config-location: classpath:mybatis/mapper/mybatis-config.xml
  type-aliases-package: com.atguigu.springcloud.entities
  # mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    io:
      seata: info

