server:
  port: 7002

# Eureka
eureka:
  instance:
    hostname: eureka7002.com # Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己
    fetch-registry: false # false表示自己为注册中心
    service-url: # 监控页面
      # 单机：挂载自己 http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群：关联别人 http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/