server:
  port: 80

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://139.155.17.127:9411
  sleuth:
    samper:
      # 采样率值介于0到1之间，1则表示全部采集
      probability: 1

# Eureka
eureka:
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己
    service-url: # 监控页面
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
#指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
#指的是建立连接后从服务器的读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign 日志以什么级别监控哪个接口
    com.atguigu.springcloud.service.PaymentFeignService: debug

# 用于服务降级，在注解@FeignClient中添加fallbackFactory属性值
feign:
  hystrix:
    enabled: true # 在Feign中开启Hystrix